name: Scrape

on:
  push:
  schedule:
    - cron: "0 4 * * *"
  workflow_dispatch:

jobs:
  scrape-latest:
    name: "scrape-latest"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: set up java
        uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
            distribution: 'temurin' # See 'Supported distributions' for available options
            java-version: '11'
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install requirements
        run: python -m pip install selenium requests pandas beautifulsoup4 tabula 
      - name: set up chromedriver
        run: 
      - uses: actions/checkout@v2
      - uses: nanasess/setup-chromedriver@master
        with:
          chromedriver-version: '88.0.4324.96'
      - run: |
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
      - name: Run Scraper
        run: python umd_scraper.py
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
      - name: Run Scraper Howard Univ.
        run: python howard_scraper.py
      - name: Commit and push if it changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
